server:
  port : 8080
  servlet :
    context-path :
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/domelist?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: user
    password: wjdgns001!A
mybatis:
  mapper-locations: mybatis/*.xml
  type-aliases-package: com.domelist.dome.dto